server:
   port: 8888
spring:
   application:
      name: shipper-service
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:tcp://localhost/~/${database:2019_10_HIBERNATE_WITH_SPRING_HPE}
      username: sa
      password: 
   jpa:
      hibernate:
         ddl-auto: none
         
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka